### ISSUE TITLE
while Video Playing it will gives blank screen .How Can I  solve it?

### ISSUE THREAD

**Issue by sriharianu** [hoang89yenthe/AndroidRTCRecorder_Libjingle_ver11139#1]
Hi , Sir 
We are download your project from git hub and import into android studio . We need screen recording feature in when video call is running ,  we are using  your recording functionality . It is Working and mp4 video saved into the sd card . But when we played in our android mobile player the video is completely blank . But audio is recorded and played well . Just tell me  the problem in project , and suggest me sample source code for Android screen recording feature . Please respond , it very helpful us .

**Comment by hoang89yenthe** [comment]
Please check https://github.com/pchab/AndroidRTC, to record video you can see https://github.com/Everyplay/everyplay-android-sdk

**Comment by sriharianu** [comment]
Thank you for your responding . (  https://github.com/Everyplay/everyplay-android-sdk ) I already integrated in android studio . I am getting gradle synchronising  errors in my project .

**Comment by sriharianu** [comment]
Hi Sir,
How to record video using everyplay library.Please give me sample code.It is very helpfull to me.
