### ISSUE TITLE
how to improve audio quality?

### ISSUE THREAD

**Issue by sriharianu** [hoang89yenthe/AndroidRTCRecorder_Libjingle_ver11139#2]
Hi sir,
I am importing your  project in my android environment.Now video call working fine.But not fine with audio.how to increase speakers volume while video call is running . Which type of audio codecs used in webrtc .

**Comment by hoang89yenthe** [comment]
You can use Audio Manager (https://developer.android.com/reference/android/media/AudioManager.html) .The default audio codec is VP9

**Comment by sriharianu** [comment]
Thank you for your responding .
